import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Noteset - fitness app</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Title />
    </>
  );
};

const Title = () => {
  return (
    <div>
      <h1>Hi, I am Noteset, your personal workout tracker!</h1>
      <p>
        To learn more about me, checkout{" "}
        <a href="https://github.com/Srkuleo" target="_blank" rel="noreferrer">
          this
        </a>{" "}
        git repo.
      </p>
    </div>
  );
};

export default Home;
