import { type NextPage } from "next";
import Head from "next/head";
import { MainWrapper, LeftWrapper, RightWrapper } from "../components/wrappers";
import { SignInForm, Logo } from "../components/sign-in-page-ls";
import { AppIntroduction } from "../components/sign-in-page-rs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Noteset - Sign In</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>
        <MainWrapper>
          <LeftWrapper>
            <Logo />
            <SignInForm />
          </LeftWrapper>
          <RightWrapper>
            <AppIntroduction />
          </RightWrapper>
        </MainWrapper>
      </main>
    </>
  );
};

export default Home;
